dist: trusty
sudo: required
language: ruby
rvm:
  2.6.0
addons:
  chrome: stable
cache:
- bundler
- yarn
- npm
before_install:
- npm i -g node@latest
- sudo add-apt-repository -y ppa:isage-dna/imagick
- sudo apt-get update -qq
- sudo apt-get install -y libsndfile-dev lame
- sudo apt-get -y --reinstall install imagemagick
- printf "\n" | pecl install imagick-beta
- yarn
before_script:
- mysql -e 'create database alonetone_test';
- gem update --system
- bundle exec rake copy_config db:drop db:create db:schema:load
- bundle exec rake db:seed
script: bundle exec rake spec
notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    on_success: always
    on_failure: always
    template:
    - ":%{result}: Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>)
      by %{author}"
    rooms:
      secure: Qhq4djpBKwf8yChyLLADLqy1yUquqmCT/KkVL5HRV2wpONV3BZ/fBf5EFf4gzyeZiQZybtuiREe3ZsgR7OFgHH5NoHmSqQJz+Bf361mrMCd/4uyNQdIbFV7+2xfbRA1YadNSE+LG/ubMSVgM2Dp4spGZOZ+oYJVoUIikGDZIfg8WIOdR5RQGb+MPlpn8UPTirSAGtF4RIkJmlwz9aq/dGokpWEcXWNlXK+Hx9zSpkFzFaBmDRZVp5nC05MrXXCXQa5a4vUW1S5v8mQrBuJUcpWSMlbOuF8zI+m5VyAaXU4PF4gD636MqsbkzSUqQnLlGkbnMRmuQbPXc8A/qjVr/w45hMqB8J0zvXqsyPmaFKZ8FNkAnpbRUc7sUpLVlaR7PcZpg8J4dQUXlSu9X22hwLox1hnM2TQevDWTRYOKlrfibFrmHMS6XqevGBQpHkJKOKB0BJ47JSwN1BcJoSE18z/U6rdU2ck0NfNsZVDhM+3Y4Vs8UGNwI4z0XT63jcn5z1773rOSpPH08KmvKWi5O61bail1EprxoJ1qIvGn+MRH2ai4NmG23CJ8wf0pDntQ+kV2inw2XTjHZbt8jLaucAgKz2OM7LF5P4dQn5UjZm+PO2toZh7XQrj0Bpy1IoioFMiu3sM/2+f6+juLwIeVcFpGA218HD+p4KoeenOIKx/4=
env:
  global:
  - S3_BUCKET_NAME=junkinthetrunk
  - secure: O45V0oniMMy2SfZ4GlCafzkPyvbNvf+ppUd9hu82RLQpANI7l7NKGa7gCW/FYlcDDcIuUkut6D21eEWwPG0x8bLqSIoE9x5kSK6xuOoqCKHkznWxsfMVI+CjoVAkekvS8iDlnu3BTIa7m0264uaJovGhUDWN43YJ+Z9sRxwYh8g=
dd:
  secure: P8Dl8rMYdZxUCBvSsGiFgaDIdut8tcsNoOngzNb4n8GG5M9+8nGyLNr/jKGmeBW4cBig2pFCfCzaR9J4Uk29dB5oS11as3fC/+wFT9pOnSBGNYErMpKKii4puVYOylEAynhiW/u8pbWpnjvhyyUaWy1if1oJcdL1qfPQ+VZPARCz6ru97PISGviOvMTy/FeLzXBt1g8yIuzNHme4nkqFufzlKGLgOietTkXTbqZGDstVlbmefwuZrD/d6vMBfu98W1CqlguO+hcpW/r7HIxcgSnqAftZ02eKcpbyxx3zkn3wQkA+kySTRC3NsXwzojw16jNZpu0Vbr4DIwi21y0YMusp15+5XcHUibaYnFdbxbAIcsBnrliRdikKz0lTMYws0JkHyftwFZJuDJZG1XOAo/Fsb7CPz9h5TPQaMlomxje72SB8wtXt4Qb60uPQHKRHqMKVFVqG/1WQ0JGVKOaP4BbjaOXrutDpkdQIV1xP+aXmy99TCwwfIpH90pPyTUkeRDaF9vWLauXEVCf22d31BGwOnfByRRZYrgTlru4XXodZLY+QIdqzZ4mLinrcotaiy9AYc0h06UzWNu1ZQSXqekrPGvGCJfJ8j0f578GO3wHNpwjZtIwGh/OGWIgHsLp8zvPdDENsUElaF0/FkKXkRbrU8x8NyJrYfQHrNNDhnto=
