development:
  adapter: mysql2
  encoding: utf8mb4
  database: alonetone_development
  pool: 5
  host: localhost
  variables:
    sql_mode: TRADITIONAL
test:
  adapter: mysql2
  encoding: utf8mb4
  database: alonetone_test
  pool: 5
  host: localhost
  variables:
    sql_mode: TRADITIONAL
